import offProfile from "@/public/images/off-profile.svg";

export const offUser = {
	login: "username",
	id: "0000000",
	avatar_url: offProfile.src,
	gravatar_id: "",
	url: "",
	html_url: "",
	followers_url: "",
	following_url: "",
	gists_url: "",
	starred_url: "",
	subscriptions_url: "",
	organizations_url: "",
	repos_url: "",
	events_url: "",
	received_events_url: "",
	type: "User",
	site_admin: false,
	name: "Nome e Sobrenome",
	company: null,
	blog: "",
	location: "Localização",
	email: null,
	hireable: true,
	bio: "Bio",
	twitter_username: null,
	public_repos: 0,
	public_gists: 0,
	followers: 0,
	following: 0,
	created_at: "1111-01-01T00:00:00",
	updated_at: "1111-01-01T00:00:00",
};
