import GlobalStyles from "@/styles/GlobalStyles";
import StyledComponentsRegistry from "./registry";

import { Bricolage_Grotesque } from "next/font/google";

const bricolageGrotesque = Bricolage_Grotesque({
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<>
			<html
				lang='pt-br'
				className={bricolageGrotesque.className}>
				<body>
					<StyledComponentsRegistry>
						<GlobalStyles />
						{children}
					</StyledComponentsRegistry>
				</body>
			</html>
		</>
	);
}
